TelefonVeAdresDefteriProjesi/TelefonVeAdresDefteriProjesi/Models/ErrorViewModel.cs
using System;

namespace TelefonVeAdresDefteriProjesi.Models
{
    public class ErrorViewModel
    {
        public string RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
    }
}

TelefonVeAdresDefteriProjesi/TelefonVeAdresDefteriProjesi/Controllers/AddressAndPhoneController.cs
using BusinessLayer.Concrete;
using DataAcessLayer.EntityFramework;
using EntityLayer.Concrete;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace TelefonVeAdresDefteriProjesi.Controllers
{
    public class AddressAndPhoneController : Controller
    {
        // Burada AddressPhoneManager sınıfından bir nesne türettik.
        AddressAndPhoneManager ad = new AddressAndPhoneManager(new EfAddressAndPhoneRepository());
        public IActionResult Index()
        {
            var values = ad.GetList();
            return View(values);
        }
        [HttpGet]
        public IActionResult TelefonVeAdresEkle()
        {
            return View();
        }
        // Burası Ekleme yapma sayfasındaki butona basınca tetikleniyor.
        [HttpPost]
        public IActionResult TelefonVeAdresEkle(AddressAndPhone p)
        {
            ad.TAdd(p);
            return RedirectToAction("Index");
        }
        // Burada güncellenecek satırı id'sine göre çekiyoruz.
        [HttpGet]
        public IActionResult TelefonVeAdresGuncelle(int id)
        {
            var values = ad.GetById(id);
            return View(values);
        }
        // Burada da ise çektiğimiz değeri güncelleyip post ediyoruz.
        [HttpPost]
        public IActionResult TelefonVeAdresGuncelle(AddressAndPhone p)
        {
            ad.TUpdate(p);
            return RedirectToAction("Index");
        }
        // İlk önce bir değişken oluşturup onu id'sine göre çekiyoruz.
        // Ardından delte komutunu yazıp silme işlemimizi gerçekleştiriyoruz.
        public IActionResult TelefonVeAdresSil(int id)
        {
            var values = ad.GetById(id);
            ad.TDelete(values);
            return RedirectToAction("Index");
        }
    }
}

TelefonVeAdresDefteriProjesi/TelefonVeAdresDefteriProjesi/Controllers/HomeController.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.Extensions.Logging;
using System;
using System.Collections.Generic;
using System.Diagnostics;
using System.Linq;
using System.Threading.Tasks;
using TelefonVeAdresDefteriProjesi.Models;

namespace TelefonVeAdresDefteriProjesi.Controllers
{
    public class HomeController : Controller
    {
        private readonly ILogger<HomeController> _logger;

        public HomeController(ILogger<HomeController> logger)
        {
            _logger = logger;
        }

        public IActionResult Index()
        {
            return View();
        }

        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }
    }
}

TelefonVeAdresDefteriProjesi/TelefonVeAdresDefteriProjesi/Controllers/LoginController.cs
using DataAcessLayer.Concrete;
using EntityLayer.Concrete;
using Microsoft.AspNetCore.Authentication;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Security.Claims;
using System.Threading.Tasks;

namespace TelefonVeAdresDefteriProjesi.Controllers
{
    [AllowAnonymous]
    public class LoginController : Controller
    {
        [HttpGet]
        public IActionResult Index()
        {
            return View();
        }
        // Burada asenkronik bir yapı kullandık.
        [HttpPost]
        public async Task<IActionResult> Index(User p)
        {
            Context c = new Context();
            // FirstOrDefault tek değer sorgusu yapmak için kullanılır.
            var datavalue = c.Users.FirstOrDefault(x => x.Mail == p.Mail && x.Password == p.Password);
            if (datavalue != null)
            {
                //Claim'ler talep oluşturmak, kullanıcı bilgisi tutmak ve bu bilgilere göre yetkilendirme yapmamızı sağlar.
                var claims = new List<Claim>()
                {
                    new Claim(ClaimTypes.Name,p.Mail)
                };
                // ClaimsIdentity'nin parantez içerisine tanımlamış olduğumuz komutların herbiri aslında bir üst satırındaki 
                // tanımlanan değeri alır.
                // "a" değeri ise belirtilen talepler ve kimlik doğrulama türü ile ClaimsIdentity sınıfının yeni bir örneğini başlatır.
                var useridentity = new ClaimsIdentity(claims,"a");
                ClaimsPrincipal principal = new ClaimsPrincipal(useridentity);
                // Gelen değeri şifreli formatta cookie oluşturması için aşağıdaki kod satırını yazarız.
                await HttpContext.SignInAsync(principal);
                return RedirectToAction("Index","Home");
            }
            else
            {
                return View();
            }
        }
    }
}

TelefonVeAdresDefteriProjesi/TelefonVeAdresDefteriProjesi/Controllers/PersonController.cs
using BusinessLayer.Concrete;
using DataAcessLayer.Concrete;
using DataAcessLayer.EntityFramework;
using EntityLayer.Concrete;
using Microsoft.AspNetCore.Mvc;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace TelefonVeAdresDefteriProjesi.Controllers
{
    public class PersonController : Controller
    {
        PersonManager pm = new PersonManager(new EfPersonRepository());
        public IActionResult Index()
        {
            var values = pm.GetList();
            return View(values);
        }
        [HttpGet]
        public IActionResult KayıtEkle()
        {
            return View();
        }
        [HttpPost]
        public IActionResult KayıtEkle(Person p)
        {
            pm.TAdd(p);
            return RedirectToAction("Index");
        }
        [HttpGet]
        public IActionResult KayıtGuncelle(int id)
        {
            var values = pm.GetById(id);
            return View(values);
        }
        [HttpPost]
        public IActionResult KayıtGuncelle(Person p)
        {
            pm.TUpdate(p);
            return RedirectToAction("Index");
        }
        public IActionResult KayıtSil(int id)
        {
            var values = pm.GetById(id);
            pm.TDelete(values);
            return RedirectToAction("Index");
        }
    }
}

TelefonVeAdresDefteriProjesi/TelefonVeAdresDefteriProjesi/Controllers/RegisterController.cs
using BusinessLayer.Concrete;
using BusinessLayer.ValidationRules;
using DataAcessLayer.EntityFramework;
using EntityLayer.Concrete;
using FluentValidation.Results;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace TelefonVeAdresDefteriProjesi.Controllers
{
    public class RegisterController : Controller
    {
        UserManager um = new UserManager(new EfUserRepository());
        [HttpGet]
        public IActionResult Index()
        {
            return View();
        }
        // Burada önce User sınıfından bir p parametresi türetiyoruz.
        // 
        [HttpPost]
        public IActionResult Index(User p)
        {
            // Aşağıdaki iki satırda validasyonların kontrolünü sağlıyoruz.
            UserValidator uv = new UserValidator();
            ValidationResult results = uv.Validate(p);
            if (results.IsValid)
            {
                // Eğer sonuçlar geçerli ise aşağıdaki işlemleri yap.
                um.TAdd(p);
                return RedirectToAction("Index", "Home");
            }
            // Validasyon koşullarını sağlamıyorsa bu işlemler yapılır. 
            else
            {
                foreach (var item in results.Errors)
                {
                    // Modelin durumuna bir error ekleyeceğiz error durumları ise parantez içindedir.
                    ModelState.AddModelError(item.PropertyName, item.ErrorMessage);
                }
            }
            // İşlem geçersiz ise bize bir View döner ve hata ortadan kalkar.
            return View();
        }
    }
}

TelefonVeAdresDefteriProjesi/TelefonVeAdresDefteriProjesi/Views/AddressAndPhone/Index.cshtml
@using EntityLayer.Concrete
@model List<AddressAndPhone>
@{
    ViewData["Title"] = "Index";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<table class="table table-bordered">
    <tr>
        <th>AdresVeTelefonID</th>
        <th>KişiID</th>
        <th>Adres</th>
        <th>Telefon No</th>
        <th>İlçe</th>
        <th>İl</th>
        <th>Düzenle</th>
        <th>Sil</th>
    </tr>
    <tbody>
        @foreach (var adph in Model)
        {
        <tr>
            <td>@adph.AddressAndPhoneID</td>
            <td>@adph.PersonID</td>
            <td>@adph.Address</td>
            <td>@adph.PhoneNumber</td>
            <td>@adph.State</td>
            <td>@adph.City</td>
            <td><a href="/AddressAndPhone/TelefonVeAdresGuncelle/@adph.AddressAndPhoneID" class="btn btn-info">Güncelle</a></td>
            <td><a href="/AddressAndPhone/TelefonVeAdresSil/@adph.AddressAndPhoneID" class="btn btn-danger">Sil</a></td>
        </tr>
        }
    </tbody>
</table>
<a href="/AddressAndPhone/TelefonVeAdresEkle/" class="btn btn-primary">Yeni Kayıt Ekle</a>

TelefonVeAdresDefteriProjesi/TelefonVeAdresDefteriProjesi/Views/AddressAndPhone/TelefonVeAdresEkle.cshtml
@{
    ViewData["Title"] = "TelefonVeAdresEkle";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h1>TelefonVeAdresEkle</h1>

<form class="form-group" method="post">
    <br />
    @Html.Label("KişiID")
    <input type="text" name="PersonID" class="form-control" />
    <br />
    @Html.Label("Adres")
    <input type="text" name="Address" class="form-control" />
    <br />
    @Html.Label("Telefon Numarası")
    <input type="text" name="PhoneNumber" class="form-control" />
    <br />
    @Html.Label("İlçe")
    <input type="text" name="State" class="form-control" />
    <br />
    @Html.Label("İl")
    <input type="text" name="City" class="form-control" />
    <br />
    <button class="btn btn-primary">Ekle</button>
</form>

TelefonVeAdresDefteriProjesi/TelefonVeAdresDefteriProjesi/Views/AddressAndPhone/TelefonVeAdresGuncelle.cshtml
@model EntityLayer.Concrete.AddressAndPhone
@{
    ViewData["Title"] = "TelefonVeAdresGuncelle";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h1>Telefon Ve Adres Guncelle</h1>
@using (Html.BeginForm("TelefonVeAdresGuncelle", "AddressAndPhone", FormMethod.Post))
{
    @Html.HiddenFor(x => x.AddressAndPhoneID)
    <br />
    @Html.Label("KişiID")
    @Html.TextBoxFor(x => x.PersonID, new { @class = "form-control" })
    <br />
    @Html.Label("Adres")
    @Html.TextBoxFor(x => x.Address, new { @class = "form-control" })
    <br />
    @Html.Label("Telefon Numarası")
    @Html.TextBoxFor(x => x.PhoneNumber, new { @class = "form-control" })
    <br />
    @Html.Label("İlçe")
    @Html.TextBoxFor(x => x.State, new { @class = "form-control" })
    <br />
    @Html.Label("İl")
    @Html.TextBoxFor(x => x.City, new { @class = "form-control" })
    <br />
    <button class="btn btn-success">Güncelle</button>
}

TelefonVeAdresDefteriProjesi/TelefonVeAdresDefteriProjesi/Views/Home/Index.cshtml
@{
    ViewData["Title"] = "Home Page";
}

<div class="text-center" color="blue">
    <h1 class="display-4">Telefon Ve Adres Defteri Projesine Hoşgeldiniz</h1>
</div>

TelefonVeAdresDefteriProjesi/TelefonVeAdresDefteriProjesi/Views/Login/Index.cshtml
@{
    ViewData["Title"] = "Index";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<section class="main-content-w3layouts-agileits">
    <div class="container">
        <h3 class="tittle">Oturum Aç</h3>
        <div class="row inner-sec">
            <div class="login p-5 bg-light mx-auto mw-100">
                <form method="post">
                    <div class="form-group">
                        <label for="exampleInputEmail1 mb-2">E-Mail Adresi</label>
                        <input type="email" class="form-control" name="Mail" id="exampleInputEmail1" aria-describedby="emailHelp" placeholder="" required="">
                        <small id="emailHelp" class="form-text text-muted">Biz mail adresini kimseyle paylaşmayacağız.</small>
                    </div>
                    <div class="form-group">
                        <label for="exampleInputPassword1 mb-2">Şifre</label>
                        <input type="password" class="form-control" name="Password" id="exampleInputPassword1" placeholder="" required="">
                    </div>
                    <div class="form-check mb-2">
                        <input type="checkbox" class="form-check-input" id="exampleCheck1">
                        <label class="form-check-label" for="exampleCheck1">Beni Hatırla</label>
                    </div>
                    <button type="submit" class="btn btn-primary submit mb-4">Giriş Yap</button>
                    <p><a href="/Register/Index/">Bir hesabın yok mu?</a></p>
                </form>
            </div>
        </div>
    </div>
</section>

TelefonVeAdresDefteriProjesi/TelefonVeAdresDefteriProjesi/Views/Person/Index.cshtml
@using EntityLayer.Concrete
@model List<Person>
@{
    ViewData["Title"] = "Index";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<table class="table table-bordered">
    <tr>
        <th>KişiID</th>
        <th>Ad</th>
        <th>Soyad</th>
        <th>Yaş</th>
        <th>Düzenle</th>
        <th>Sil</th>
    </tr>
    <tbody>
        @foreach (var prsn in Model)
        {
            <tr>
                <td>@prsn.PersonID</td>
                <td>@prsn.Name</td>
                <td>@prsn.Surname</td>
                <td>@prsn.Age</td>
                <td><a href="/Person/KayıtGuncelle/@prsn.PersonID" class="btn btn-info">Güncelle</a></td>
                <td><a href="/Person/KayıtSil/@prsn.PersonID" class="btn btn-danger">Sil</a></td>
            </tr>
        }
    </tbody>
</table>
<a href="/Person/KayıtEkle/" class="btn btn-primary">Yeni Kayıt Ekle</a>

TelefonVeAdresDefteriProjesi/TelefonVeAdresDefteriProjesi/Views/Person/KayıtEkle.cshtml
@{
    ViewData["Title"] = "KayıtEkle";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h1>KayıtEkle</h1>
<form class="form-group" method="post">
    <br />
    @Html.Label("Ad")
    <input type="text" name="Name" class="form-control" />
    <br />
    @Html.Label("Soyad")
    <input type="text" name="Surname" class="form-control"/>
    <br />
    @Html.Label("Yaş")
    <input type="text" name="Age" class="form-control"/>
    <br />
    <button class="btn btn-primary">Ekle</button>
</form>

TelefonVeAdresDefteriProjesi/TelefonVeAdresDefteriProjesi/Views/Person/KayıtGuncelle.cshtml
@model EntityLayer.Concrete.Person
@{
    ViewData["Title"] = "KayıtGuncelle";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h1>KayıtGuncelle</h1>
@using (Html.BeginForm("KayıtGuncelle", "Person", FormMethod.Post))
{
    @Html.HiddenFor(x=>x.PersonID)
    <br />
    @Html.Label("Ad")
    @Html.TextBoxFor(x => x.Name, new { @class = "form-control" })
    <br />
    @Html.Label("Soyad")
    @Html.TextBoxFor(x => x.Surname, new { @class = "form-control" })
    <br />
    @Html.Label("Yaş")
    @Html.TextBoxFor(x => x.Age, new { @class = "form-control" })
    <br />
    <button class="btn btn-success">Güncelle</button>
}

TelefonVeAdresDefteriProjesi/TelefonVeAdresDefteriProjesi/Views/Register/Index.cshtml
@model EntityLayer.Concrete.User
@{
    ViewData["Title"] = "Index";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<script src="https://unpkg.com/sweetalert/dist/sweetalert.min.js"></script>
<script src="~/lib/jquery/dist/jquery.js"></script>

<section class="main-content-w3layouts-agileits">
    <div class="container">
        <h3 class="tittle">Kullanıcı Kayıt Sayfası</h3>
        <div class="inner-sec">
            <div class="login p-5 bg-light mx-auto mw-100">
                @using (Html.BeginForm("Index", "Register", FormMethod.Post))
                {
                    <div class="form-row">
                        <div class="col-md-6 mb-3">
                            <label for="validationCustom01">Adınız</label>
                            @Html.TextBoxFor(x => x.Name, new { @class = "form-control" })
                            @Html.ValidationMessageFor(x => x.Name, "", new { @class = "text-danger" })
                            @*<input type="text" class="form-control" id="validationDefault01" name="WriterName" placeholder="" required="">*@
                        </div>
                        <div class="col-md-6 mb-3">
                            <label for="validationCustom02">Soyadınız</label>
                            @Html.TextBoxFor(x => x.Surname, new { @class = "form-control" })
                            @Html.ValidationMessageFor(x => x.Surname, "", new { @class = "text-danger" })
                        </div>
                    </div>
                    <div class="form-row">
                        <div class="form-group col-md-6">
                            <label for="exampleInputPassword1 mb-2">Mail Adresiniz</label>
                            @Html.TextBoxFor(x => x.Mail, new { @class = "form-control" })
                            @Html.ValidationMessageFor(x => x.Mail, "", new { @class = "text-danger" })
                        </div>
                        <div class="form-group col-md-6">
                            <label for="exampleInputPassword2 mb-2">Şifre</label>
                            @Html.TextBoxFor(x => x.Password, new { @class = "form-control" })
                            @Html.ValidationMessageFor(x => x.Password, "", new { @class = "text-danger" })
                        </div>
                    </div>
                    <button type="submit" class="btn btn-primary submit mb-4">Kayıt Ol</button>
                    <p>
                        <a href="#" id="btn1">Tüm şartları okudum, kabul ediyorum.</a>
                    </p>
                }
            </div>
        </div>
    </div>
    <br />
    <script>
        $('#btn1').click(function () {
            swal("Kullanım Site Kabul Şartları","Sitemize verdiğiniz mail adresi üzerinden bilgi ve haber e-postaları spam ölçüsüne varmadan gönderilmeye devam edilecektir. Eğer e-posta bülteninden çıkmak isterseniz mail ileti dizisini durdurabilirsiniz, şifre ve mail adresleriniz şifrelenmiş formatta herhangi bir kullanıcının göremeyeceği şekilde veri tabanlarınızda saklanmaktadır.");
        });
    </script>
</section>

TelefonVeAdresDefteriProjesi/TelefonVeAdresDefteriProjesi/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@*@ViewData["Title"] -*@ Telefon Ve Adres Defteri</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">Telefon Ve Adres Defteri</a>
                <button class="navbar-toggler" type="button" data-toggle="collapse" data-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Person" asp-action="Index">Kişiler</a>
                        </li>

                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="AddressAndPhone" asp-action="Index">Adres Ve Telefon</a>
                        </li>

                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Register" asp-action="Index">Kayıt Ol</a>
                        </li>

                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Login" asp-action="Index">Giriş Yap</a>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2022 - Telefon Ve Adres Defteri Projesi
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>